global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rabbitmq-node1"
    static_configs:
      - targets: ["rabbitmq1:15692"]
    metrics_path: /metrics

  - job_name: "rabbitmq-node2"
    static_configs:
      - targets: ["rabbitmq2:15692"]
    metrics_path: /metrics

  - job_name: "rabbitmq-node3"
    static_configs:
      - targets: ["rabbitmq3:15692"]
    metrics_path: /metrics

  - job_name: "rabbitmq-node4"
    static_configs:
      - targets: [ "rabbitmq4:15692" ]
    metrics_path: /metrics

  - job_name: "producer"
    # static_configs:
    #   - targets: ["producer:8081"]
    dns_sd_configs:
      - names:
          - 'tasks.producer' # Docker service discovery name
        type: 'A'
        port: 8081
    metrics_path: /actuator/prometheus

  - job_name: "consumer"
    # static_configs:
    #  - targets: ["consumer:8080"]
    dns_sd_configs:
      - names:
          - 'tasks.consumer' # Docker service discovery name
        type: 'A'
        port: 8080
    metrics_path: /actuator/prometheus
