global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq1'
    static_configs:
      - targets: ['rabbitmq1:15692']
        labels:
          instance: 'rabbitmq1'

  - job_name: 'rabbitmq2'
    static_configs:
      - targets: ['rabbitmq2:15692']
        labels:
          instance: 'rabbitmq2'

  - job_name: 'rabbitmq3'
    static_configs:
      - targets: ['rabbitmq3:15692']
        labels:
          instance: 'rabbitmq3' 