server:
  port: 8080

spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:my-consumer-group}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      enable-auto-commit: false
      properties:
        isolation.level: read_committed
      max-poll-records: 500
      fetch-min-size: 1
      fetch-max-wait: 500 