spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 1  # Handling one message at a time

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO 

ollama:
  api:
    url: ${OLLAMA_API_URL:http://localhost:11434/api/generate}
