server:
  port: 8080

spring:
  application:
    name: kafka-producer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      properties:
        enable.idempotence: ${SPRING_KAFKA_PRODUCER_PROPERTIES_ENABLE_IDEMPOTENCE:true}
      acks: ${SPRING_KAFKA_PRODUCER_ACKS:all}
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy 