spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: INFO 
