spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    # Cluster specific configurations
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 2.0

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: INFO 
